version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:18.0.2
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: secret
    ports:
      - "8080:8080"
    volumes:
      -  ./testdata/master-realm.json:/opt/keycloak/data/import/master-realm.json
      -  ./testdata/gocloak-realm.json:/opt/keycloak/data/import/gocloak-realm.json
